databaseChangeLog:
  - changeSet:
      id: "01"
      author: cavemanfrak
      context: test
      changes:
        - loadData:
            columns:
              - column:
                  name: id
                  type: UUID
              - column:
                  name: active
                  type: BOOLEAN
              - column:
                  name: tonnage
                  type: DECIMAL(8,2)
              - column:
                  name: beam
                  type: DECIMAL(8,2)
              - column:
                  header: length
                  name: len
                  type: DECIMAL(8,2)
              - column:
                  name: draft
                  type: DECIMAL(8,2)
            relativeToChangelogFile: true
            file: v1/data/0003-01-vessel-data.csv
            tableName: vessel
            usePreparedStatements: true
            encoding: UTF-8
  - changeSet:
      id: "02"
      author: cavemanfrak
      context: test
      changes:
        - loadData:
            columns:
              - column:
                  name: vessel
                  type: UUID
              - column:
                  name: provider
                  type: ENUM
              - column:
                  name: ident
                  type: CHAR(255)
            relativeToChangelogFile: true
            file: v1/data/0003-02-identifier-data.csv
            tableName: identifier
            usePreparedStatements: true
            encoding: UTF-8